language: node_js
sudo: true
dist: trusty
node_js:
  - "4.0"
  - "6.0"
before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
install:
  - npm i -g npm
  - npm install
before_script:
  - ruby -v
script:
  - npm run danger
  - npm run lint && npm run test
notifications:
  email:
    on_failure: change
