language: node_js
dist: trusty
sudo: required
addons:
  apt:
    packages:
      - libnss3
      - google-chrome-beta
env:
  global:
    - GOOGLE_CHROME_BINARY="/usr/bin/google-chrome-beta"
    - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD="true"
node_js:
  - 6
  - 8
script:
  - node --version
  - yarn --version
  # Tests have to run before Danger runs because
  # danger-plugin-jest references the test output
  - yarn run test
  - yarn run danger
  - yarn run flow
  - yarn run lint && yarn run typescript && yarn run tslint
notifications:
  email:
    on_failure: change
cache:
  yarn: true
  bundler: true
  directories:
    - node_modules
