language: node_js
dist: trusty
node_js:
  - "6"
  - "7"
script:
  - yarn run danger run -- --verbose
  - npm run flow
  - npm run lint && npm run tslint && npm run test
notifications:
  email:
    on_failure: change
cache:
  yarn: true
  bundler: true
  directories:
    - node_modules
