language: node_js
sudo: true
dist: trusty
node_js:
  - "4.0"
  - "6.0"
install:
  - npm i -g npm
  - npm install
script:
  - npm run danger
  - npm run lint && npm run test
notifications:
  email:
    on_failure: change
