name: Inclusive Organization
on: 
  push:
    branches: master
jobs:
  invite:
    runs-on: ubuntu-latest
    steps:
      - name: Invite contributor to the organization
        uses: lekterable/inclusive-organization-action@v1.0.0
        with:
          organization: styled-components
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
